version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./apps/backend:/app
    environment:
      - ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ./apps/frontend:/app
    environment:
      - ENV=development

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
